config/routes.rb
Ldmc::Engine.routes.draw do
  get 'read_sequences', to: 'read_sequences#all'
  get 'read_generals', to: 'read_generals#all'
  resources :subjects do
    resources :read_generals
    resources :read_sequences do
      resources :lesions
    end
  end
  resources :participants
  root to: 'subjects#index'
end

app/models/ldmc/ability.rb
module Ldmc
  class Ability
    include ::CanCan::Ability

    def initialize(user)
      return if user.nil?

      if user.has_role? :admin
        can :manage, :all

      elsif user.has_role? :radiologo
        can [:index, :read, :update], Subject
        can [:index, :read, :update], ReadSequence
        can :manage, Lesion

      else
        can [:read, :update], User, :id => user.id
        cannot :index, User
      end
    end
  end
end

app/models/ldmc/lesion.rb
module Ldmc
  class Lesion
    include Mongoid::Document
    include Mongoid::Timestamps

    field :type, type: String, default: 'lesion'

    field :size_ax, type: Integer
    field :vertebral_level, type: Array; LEVEL_OPTS = ['C1','C2','C3','C4','C5','C6','C7','D1']
    field :clarity, type: String; CLARITY_OPTS = ['buena','regular','mala']
    field :spine_localization, type: Array; LOCAL_OPTS = ['Centromedular','Lateral','Anterior','Posterior']
    field :intensity_lesion, type: Float
    field :intensity_normalspine, type: Float
    field :intensity_nape, type: Float
    field :created_by

    embedded_in :read_sequence
    
    before_validation do |model|
      model.vertebral_level.reject!(&:blank?) if model.vertebral_level
      model.spine_localization.reject!(&:blank?) if model.spine_localization
    end
    
    
    
    

  end
end

app/models/ldmc/participant.rb
module Ldmc
  class Participant
    include Mongoid::Document
    include Mongoid::Timestamps

    field :type, type: String, default: 'participant'
    field :user_id, type: String
    field :role, type: String; ROLE_OPTS = ['rad1', 'rad2', 'pi']
  end
end

app/models/ldmc/read_general.rb
module Ldmc
  class ReadGeneral
    include Mongoid::Document
    include Mongoid::Timestamps

    field :type, type: String, default: 'read general'
    field :indication, type: String
    field :read_ann, type: String
    field :lesion_dir, type: Array; LESION_OPT = ['periventriculares','sustancia blanca subcortical','sustancia gris','pedunculos cerebrales']
    field :level_dir, type: String
    field :level_flair, type: String
    field :updated_by

    embedded_in :subject
    
    before_validation do |model|
      model.lesion_dir.reject!(&:blank?) if model.lesion_dir
    end

  end

end

app/models/ldmc/read_sequence.rb
module Ldmc
  class ReadSequence
    include Mongoid::Document
    include Mongoid::Timestamps

    field :type, type: String, default: 'read sequence'
    
    field :sequence_name, type: String; SEQ_OPT = ['3D DIR','3D FLAIR','DP SAG','ST SAG','ST SAG','2D FLAIR']
    field :sequence_ann, type: String              
    field :nolesion_tri, type: Boolean             
    field :rad, type:String
    field :updated_by                              
                                                   
    embedded_in :subject                           
    embeds_many :lesions, class_name: 'Ldmc::Lesion'

    accepts_nested_attributes_for :lesions, :reject_if => :all_blank, :allow_destroy => true
   

  end

end

app/models/ldmc/subject.rb
module Ldmc
  class Subject
    include Mongoid::Document
    include Mongoid::Slug
    include Mongoid::Timestamps

    field :type, type: String, default: 'subject'
    field :identification, type: String
    field :sex, type: String; SEX_OPTS = ['femenino','masculino']
    field :age, type: Integer

    slug :identification

    embeds_many :read_sequences, class_name: 'Ldmc::ReadSequence'
    embeds_one :read_general, class_name: 'Ldmc::ReadGeneral'

    accepts_nested_attributes_for :read_sequences, :reject_if => :all_blank, :allow_destroy => true
    accepts_nested_attributes_for :read_general, :reject_if => :all_blank, :allow_destroy => true

    validates_presence_of :identification

  end
end

app/controllers/ldmc/application_controller.rb
module Ldmc
  class ApplicationController < ActionController::Base
    
    layout 'application'
  end
end

app/controllers/ldmc/lesions_controller.rb
module Ldmc
  class LesionsController < ApplicationController
    before_action :load_subject, only: [:show, :edit, :update, :new, :create, :destroy]
    before_action :load_read_sequence, only: [:show, :edit, :update, :new, :create, :destroy]
    before_action :set_lesion, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def new
      @lesion = @read_sequence.lesions.build
    end

    def create
      @lesion = @read_sequence.lesions.build(lesion_params)

      respond_to do |format|
        if @lesion.save
          format.html { redirect_to [@subject, @read_sequence, @lesion], notice: 'Lesion was successfully created.' }
          format.json { render action: 'show', status: :created, location: @lesion }
        else
          format.html { render action: 'new' }
          format.json { render json: @lesion.errors, status: :unprocessable_entity }
          end
      end
    end

    def update
      respond_to do |format|
        if @lesion.update_attributes(lesion_params)
         format.html { redirect_to [@subject, @read_sequence, @lesion], notice: 'Lesion was successfully updated.' }
         format.json { head :no_content }
        else
         format.html { render action: 'edit' }
        format.json { render json: @lesion.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @lesion.destroy
      respond_to do |format|
        format.html { redirect_to [@subject, @read_sequence, @lesion], notice: 'Lesion was successfully deleted.'  }
        format.json { head :no_content }
      end
    end


    private

    def set_lesion
      @lesion = @read_sequence.lesions.find(params[:id])
    end

    def load_read_sequence
      @read_sequence = @subject.read_sequences.find(params[:read_sequence_id])
    end

    def load_subject
      @subject = Subject.find(params[:subject_id])
    end

    def lesion_params
      params.require(:lesion)
            .permit(:type,
                    :size_ax,
                    {vertebral_level: []},
                    :clarity,
                    {spine_localization: []},
                    :intensity_lesion,
                    :intensity_normalspine,
                    :intensity_nape,
                    :created_by
                    )
    end
  end
end

app/controllers/ldmc/participants_controller.rb
module Ldmc
  class ParticipantsController < ApplicationController
    before_action :set_participant, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    def index
      @participants = Participant.all
    end

    def show
    end

    def new
      @participant = Participant.new
    end

    def edit
    end

    def create
      @participant = Participant.new(participant_params)

      respond_to do |format|
        if @participant.save
          format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
          format.json { render action: 'show', status: :created, location: @participant }
        else
          format.html { render action: 'new' }
          format.json { render json: @participant.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @participant.update(participant_params)
          format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @participant.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @participant.destroy
      respond_to do |format|
        format.html { redirect_to participants_url }
        format.json { head :no_content }
      end
    end

    private

    def set_participant
      @participant = Participant.find(params[:id])
    end

    def participant_params
      params.require(:participant).permit(:user_id, :role)
    end

  end
end

app/controllers/ldmc/read_generals_controller.rb
require_dependency "ldmc/application_controller"

module Ldmc
  class ReadGeneralsController < ApplicationController
    before_action :load_subject, only: [:index, :show, :edit, :update, :new, :create, :destroy]
    before_action :set_read_general, only: [:show, :edit, :update]

    def all
      @read_generals = Subject.all.map {|s| s.read_general}.flatten
      @sorted_generals= @read_generals.sort {|a,b| a.read_ann.delete('P').to_i <=> b.read_ann.delete('P').to_i}
      
    end
    
    
    def show
    end

    def edit
    end

    def new
      @read_general = @subject.build_read_general
    end

    def create
      @read_general = @subject.build_read_general(read_general_params)

      respond_to do |format|
        if @read_general.save
          format.html { redirect_to [@subject, @read_general], notice: 'Read General was successfully created.' }
          format.json { render action: 'show', status: :created, location: @read_general }
        else
          format.html { render action: 'new' }
          format.json { render json: @read_general.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      
      respond_to do |format|
        @read_general.assign_attributes(read_general_params)
        @read_general.updated_by=current_user.id
        
        if @read_general.save
          format.html { redirect_to read_generals_path}
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @read_general.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    def set_read_general
      @read_general = @subject.read_general
    end
    
    def load_subject
      @subject = Subject.find(params[:subject_id])
    end

    def read_general_params
      params.require(:read_general)
            .permit(
                    {lesion_dir: []},
                    :level_dir,
                    :level_flair,
                    :read_ann,
                    :indication,
                    :updated_by
                    )
    end
  end
end

app/controllers/ldmc/read_sequences_controller.rb
module Ldmc
  class ReadSequencesController < ApplicationController
    skip_authorization_check
  
    before_action :load_subject, only: [:index, :show, :edit, :update, :new, :create, :destroy]
    before_action :set_read_sequence, only: [:show, :edit, :update, :destroy]

    def all
      if current_user.id.to_s=="5345b8dd6d61634023000000"
        @read_sequences = Subject.all.map {|s| s.read_sequences.all(rad:"1")}.flatten
      else
         @read_sequences = Subject.all.map {|s| s.read_sequences.all(rad:"2")}.flatten
      end
      
      @sorted_sequences= @read_sequences.sort {|a,b| a.sequence_ann.delete('S').to_i <=> b.sequence_ann.delete('S').to_i}
      
    end

    def index
      @read_sequences = @subject.read_sequences.all
    end

    def show
      @sorted_lesions= @read_sequence.lesions.sort {|a,b| b.size_ax <=> a.size_ax}
    end

    def edit
      @user=current_user.id
    end

    def new
      @read_sequence = @subject.read_sequences.build
    end

    def create
      @read_sequence = @subject.read_sequences.build(read_sequence_params)

      respond_to do |format|
        if @read_sequence.save
          format.html { redirect_to [@subject, @read_sequence], notice: 'Lession was successfully created.' }
          format.json { render action: 'show', status: :created, location: @read_sequence }
        else
          format.html { render action: 'new' }
          format.json { render json: @read_sequence.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
    
      respond_to do |format|
          @read_sequence.assign_attributes(read_sequence_params)
          @read_sequence.updated_by=current_user.id
          if @read_sequence.lesions.present?
            @read_sequence.nolesion_tri=false
          end
        
         if @read_sequence.save
           
          format.html { redirect_to read_sequences_path}
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @read_sequence.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_read_sequence
      @read_sequence = @subject.read_sequences.find(params[:id])
    end

    def load_subject
      @subject = Subject.find(params[:subject_id])
    end

    def read_sequence_params
      params.require(:read_sequence).permit(:sequence_name, :sequence_ann,:nolesion_tri,:rad,:updated_by,
                                            :lesions_attributes => [:id,
                                                                    :type,
                                                                    :size_ax,
                                                                    {vertebral_level: []},
                                                                    :clarity,
                                                                    {spine_localization: []},
                                                                    :intensity_lesion,
                                                                    :intensity_normalspine,
                                                                    :intensity_nape,
                                                                    :_destroy,
                                                                    :created_by])
    end
  end
end

app/controllers/ldmc/subjects_controller.rb
module Ldmc
  class SubjectsController < ApplicationController
    skip_authorization_check
    before_action :set_subject, only: [:show, :edit, :update, :destroy]

    def index
      @subjects = Subject.all
    end

    def show
    end

    def new
      @subject = Subject.new

      @subject.read_sequences.build(sequence_name: '3D DIR')
      @subject.read_sequences.build(sequence_name: '3D FLAIR')
      @subject.read_sequences.build(sequence_name: 'DP SAG')
      @subject.read_sequences.build(sequence_name: 'ST SAG')
      @subject.read_sequences.build(sequence_name: '2D FLAIR')

      @subject.build_read_general
    end

    def edit
    end

    def create
      @subject = Subject.new(subject_params)

      respond_to do |format|
        if @subject.save
          format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
          format.json { render action: 'show', status: :created, location: @subject }
        else
          format.html { render action: 'new' }
          format.json { render json: @subject.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @subject.update(subject_params)
          format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @subject.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @subject.destroy
      respond_to do |format|
        format.html { redirect_to subjects_url }
        format.json { head :no_content }
      end
    end

    private

    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:identification, :sex, :age,
                                      :read_sequences_attributes => [:id, :sequence_name, :sequence_ann, :_destroy, :rad],
                                      :read_general_attributes => [:read_ann])
    end
  end
end

app/helpers/ldmc/application_helper.rb
module Ldmc
  module ApplicationHelper
  end
end

app/views/ldmc/read_sequences/_form.html.slim
= simple_form_for([@subject, @read_sequence], html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  .row
    h3 Caracterización de las tres lesiones más grandes
    #lesions
      = f.simple_fields_for :lesions do |l|
        = render 'lesion_fields', :f => l
      .links
        = link_to_add_association 'Agregar Lesión', f, :lesions, class: 'btn btn-success'
  hr
	.row
		=f.input :nolesion_tri, as: :boolean, label: 'No hay lesion', boolean_style: :inline
  .row
    = f.button :submit, 'Guardar cambios', class: "btn btn-primary"
	=link_to "Atrás", read_sequences_path,  class: "btn btn-info"
	
	

app/views/ldmc/read_sequences/_lesion_fields.html.slim
.nested-fields
  .panel.panel-default
    .panel-heading
      .row
				.col-md-12
	  		 		h4 Lesion
	  				span.pull-right = link_to_remove_association "Eliminar Lesion", f, class: 'btn btn-danger btn-xs'
    .panel-body
      .row
        .col-md-6
          .well
            =f.input :size_ax, as: :decimal, label:'Tamaño en mm eje craneocaudal mayor'
            =f.input :vertebral_level, as: :check_boxes, collection: Ldmc::Lesion::LEVEL_OPTS, item_wrapper_class: 'checkbox-inline', label: 'Nivel vertebral (epicentro de la lesión)'
            =f.input :clarity, as: :radio_buttons, collection: Ldmc::Lesion::CLARITY_OPTS, item_wrapper_class: 'checkbox-inline', label:'Nitidez (claridad en la visualización de la lesión)'
            =f.input :spine_localization, as: :check_boxes, collection: Ldmc::Lesion::LOCAL_OPTS, item_wrapper_class: 'checkbox-inline', label:'Localización en la médula'

        .col-md-6
          .well
            h4  Intensidad de la señal
            blockquote
              small Medir ROI siempre con area 2 mm2, Seleccionar el valor promedio
            =f.input :intensity_lesion, as: :decimal, label: 'La lesión'
            =f.input :intensity_normalspine, as: :decimal, label: 'Médula normal'
            =f.input :intensity_nape, as: :decimal, label: 'Aire posterior a la nuca'
            =f.hidden_field :created_by, value: @user
      .row
        col-md-12

app/views/ldmc/read_sequences/all.html.slim
.panel.panel-primary
	.panel-heading
		h1 Lecturas por secuencia
	.panel-body
		table.table.table-striped
			tr
				th Nombre
				th
				- @sorted_sequences.each do |read|
					tr
					- if read.updated_by == current_user.id
						td = link_to read.sequence_ann, edit_subject_read_sequence_path(read.subject,read), class: 'btn btn-primary', disabled: "disabled"
					- else
						td = link_to read.sequence_ann, edit_subject_read_sequence_path(read.subject,read), class: 'btn btn-primary'					
					td
						= link_to 'Mostrar', subject_read_sequence_path(read.subject,read), class: 'btn btn-info btn-xs'
						= link_to 'Editar', edit_subject_read_sequence_path(read.subject,read), class: "btn btn-warning btn-xs"
	.panel-footer
    

app/views/ldmc/read_sequences/edit.html.slim
h1  = "Editar lectura para secuencia #{@read_sequence.sequence_ann}"

.container
	== render 'form'

app/views/ldmc/read_sequences/index.html.slim
.panel.panel-primary
  .panel-heading
    h1 Lista de lecturas por secuencia
  .panel-body
    - @read_sequences.each do |rs|
      = link_to rs.sequence_name, subject_read_sequence_path(@subject,rs)
      br
  .panel-footer

app/views/ldmc/read_sequences/new.html.slim
h1 Lectura por secuencia

.container
	== render 'form'

app/views/ldmc/read_sequences/show.html.slim
.panel.panel-default
  .panel-heading
    h3 Lectura para #{@read_sequence.sequence_ann}
  .panel-body

    table.table.table-striped
      tr
        th Lesiones:
		th Tamaño eje CC mayor
		th Nivel vertebral
		th Nitidez
		th Localizaión med.
		th Inten. lesion
		th Inten. medula
		th Inten. Aire p.nuca

      -@sorted_lesions.each_with_index do |les,index|
        tr
          td = index+1
		  td= les.size_ax
		  td= les.vertebral_level.join(", ")
		  td= les.clarity
		  td= les.spine_localization.join(", ")
		  td= les.intensity_lesion
		  td= les.intensity_normalspine
		  td= les.intensity_nape
		  td
		  
		  
	.panel-footer
    = link_to 'Editar read sequence', edit_subject_read_sequence_path(@subject,@read_sequence), class: "btn btn-primary"
	= link_to "Atrás", read_sequences_path,  class: "btn btn-info"